apiVersion: v1
kind: Service
metadata:
  name: awx-forward-service
  namespace: awx-namespace
  labels:
    service: awx-forward-service
    
spec:
  selector:
    app: ansible-awx-service  
  ports:
    - protocol: TCP
      port: 40001
      targetPort: 30590
  type: LoadBalancer

# ports:
#   - port: 5000
#     targetPort: 80
