apiVersion: v1
kind: Service
metadata:
  name: awx
  namespace: awx-namespace
  labels:
    service: ansible-awx-service-map
    
spec:
  selector:
    app: ansible-awx-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.144.201

# ports:
#   - port: 5000
#     targetPort: 80
