apiVersion: v1
kind: Service
metadata:
  name: awx
  namespace: awx-namespace
  labels:
    # Service running the backend
    service: ansible-awx-service
    
spec:
  selector:
    app: ansible-awx-service
  type: LoadBalancer
  # port mapping
  ports:
  - port: 5000
    targetPort: 80
