apiVersion: v1
kind: Service
metadata:
  name: awx
  namespace: awx-namespace
  labels:
    # Service running the backend
    service: ansible-awx-service
    
spec:
  selector:
    app: ansible-awx-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127

# ports:
#   - port: 5000
#     targetPort: 80
