apiVersion: v1
kind: Service
metadata:
  name: awx
  namespace: awx-namespace
  labels:
    service: ansible_awx_service
    
spec:
  selector:
    app: ansible-awx-service
  type: LoadBalancer
#  type: NodePort
#  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 80
#    nodePort: 30036
