apiVersion: v1
kind: Service
metadata:
  name: AWX
  labels:
    service: ansible-awx-service
spec:
  selector:
    app: ansible-awx-service
  type: LoadBalancer
#  type: NodePort
#  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 80
#    nodePort: 30036