apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: awx-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: portal.irs.environment.nsw.gov.au
    http:
      paths:
      - path: /awx
        pathType: Prefix
        backend:
          service:
            name: ansible-awx-service
            port:
                number: 80
#   rules:
#   - host: portal.irs.environment.nsw.gov.au/awx
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ansible-awx-service
#             port:
#               number: 80             
