apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder
provisioner: cinder.csi.openstack.org
reclaimPolicy: Delete
parameters:
  availability: intersect
allowVolumeExpansion: true

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: default
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# parameters:
#   availability: intersect
# provisioner: cinder.csi.openstack.org
