apiVersion: v1
data:
  secret: cEZGd0l4ZWh4R1lwVElINkZDQ3RUdHBzSEVLMURDanM=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Secret","metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"ansible-awx","app.kubernetes.io/operator-version":"0.12.0","app.kubernetes.io/part-of":"ansible-awx"},"name":"ansible-awx-broadcast-websocket","namespace":"awx-namespace"},"stringData":{"secret":"pFFwIxehxGYpTIH6FCCtTtpsHEK1DCjs"}}'
  creationTimestamp: "2021-10-25T23:21:36Z"
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: ansible-awx
    app.kubernetes.io/operator-version: 0.12.0
    app.kubernetes.io/part-of: ansible-awx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:secret: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/operator-version: {}
          f:app.kubernetes.io/part-of: {}
      f:type: {}
    manager: Swagger-Codegen
    operation: Update
    time: "2021-10-25T23:21:36Z"
  name: ansible-awx-broadcast-websocket
  namespace: awx-namespace
  resourceVersion: "2447798"
  uid: 8b3cfcc2-5d87-4ec3-963e-17b4a4e4b045
type: Opaque
