apiVersion: v1
data:
  credentials.py: REFUQUJBU0VTID0gewogICAgJ2RlZmF1bHQnOiB7CiAgICAgICAgJ0FUT01JQ19SRVFVRVNUUyc6IFRydWUsCiAgICAgICAgJ0VOR0lORSc6ICdhd3gubWFpbi5kYi5wcm9maWxlZF9wZycsCiAgICAgICAgJ05BTUUnOiAiYXd4IiwKICAgICAgICAnVVNFUic6ICJhd3giLAogICAgICAgICdQQVNTV09SRCc6ICJCQ1lzV3FCNlpYWnVQZjlCSkFpbXRGVFYwRWxvUGNlVSIsCiAgICAgICAgJ0hPU1QnOiAnYW5zaWJsZS1hd3gtcG9zdGdyZXMnLAogICAgICAgICdQT1JUJzogIjU0MzIiLAogICAgICAgICdPUFRJT05TJzogeyAnc3NsbW9kZSc6ICdwcmVmZXInLAogICAgICAgICAgICAgICAgICAgICAnc3Nscm9vdGNlcnQnOiAnL2V0Yy9wa2kvdGxzL2NlcnRzL2NhLWJ1bmRsZS5jcnQnLAogICAgICAgIH0sCiAgICB9Cn0KCkJST0FEQ0FTVF9XRUJTT0NLRVRfU0VDUkVUID0gInBGRndJeGVoeEdZcFRJSDZGQ0N0VHRwc0hFSzFEQ2pzIgo=
  execution_environments.py: R0xPQkFMX0pPQl9FWEVDVVRJT05fRU5WSVJPTk1FTlRTID0gWwogICAgeyduYW1lJzogJ0FXWCBFRSAwLjUuMCcgLCAnaW1hZ2UnOiAncXVheS5pby9hbnNpYmxlL2F3eC1lZTowLjUuMCd9LApdCkNPTlRST0xfUExBTkVfRVhFQ1VUSU9OX0VOVklST05NRU5UID0gJ3F1YXkuaW8vYW5zaWJsZS9hd3gtZWU6MC41LjAnCg==
  ldap.py: QVVUSF9MREFQX0dMT0JBTF9PUFRJT05TID0gewp9Cg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"credentials.py":"REFUQUJBU0VTID0gewogICAgJ2RlZmF1bHQnOiB7CiAgICAgICAgJ0FUT01JQ19SRVFVRVNUUyc6IFRydWUsCiAgICAgICAgJ0VOR0lORSc6ICdhd3gubWFpbi5kYi5wcm9maWxlZF9wZycsCiAgICAgICAgJ05BTUUnOiAiYXd4IiwKICAgICAgICAnVVNFUic6ICJhd3giLAogICAgICAgICdQQVNTV09SRCc6ICJCQ1lzV3FCNlpYWnVQZjlCSkFpbXRGVFYwRWxvUGNlVSIsCiAgICAgICAgJ0hPU1QnOiAnYW5zaWJsZS1hd3gtcG9zdGdyZXMnLAogICAgICAgICdQT1JUJzogIjU0MzIiLAogICAgICAgICdPUFRJT05TJzogeyAnc3NsbW9kZSc6ICdwcmVmZXInLAogICAgICAgICAgICAgICAgICAgICAnc3Nscm9vdGNlcnQnOiAnL2V0Yy9wa2kvdGxzL2NlcnRzL2NhLWJ1bmRsZS5jcnQnLAogICAgICAgIH0sCiAgICB9Cn0KCkJST0FEQ0FTVF9XRUJTT0NLRVRfU0VDUkVUID0gInBGRndJeGVoeEdZcFRJSDZGQ0N0VHRwc0hFSzFEQ2pzIgo=","execution_environments.py":"R0xPQkFMX0pPQl9FWEVDVVRJT05fRU5WSVJPTk1FTlRTID0gWwogICAgeyduYW1lJzogJ0FXWCBFRSAwLjUuMCcgLCAnaW1hZ2UnOiAncXVheS5pby9hbnNpYmxlL2F3eC1lZTowLjUuMCd9LApdCkNPTlRST0xfUExBTkVfRVhFQ1VUSU9OX0VOVklST05NRU5UID0gJ3F1YXkuaW8vYW5zaWJsZS9hd3gtZWU6MC41LjAnCg==","ldap.py":"QVVUSF9MREFQX0dMT0JBTF9PUFRJT05TID0gewp9Cg=="},"kind":"Secret","metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"ansible-awx","app.kubernetes.io/operator-version":"0.12.0","app.kubernetes.io/part-of":"ansible-awx"},"name":"ansible-awx-app-credentials","namespace":"awx-namespace"}}'
  creationTimestamp: "2021-10-25T23:21:59Z"
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: ansible-awx
    app.kubernetes.io/operator-version: 0.12.0
    app.kubernetes.io/part-of: ansible-awx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:credentials.py: {}
        f:execution_environments.py: {}
        f:ldap.py: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/operator-version: {}
          f:app.kubernetes.io/part-of: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"6bba44bc-763b-4b0b-afd4-f0650a61b97d"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:type: {}
    manager: Swagger-Codegen
    operation: Update
    time: "2021-10-25T23:21:59Z"
  name: ansible-awx-app-credentials
  namespace: awx-namespace
  ownerReferences:
  - apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    name: ansible-awx
    uid: 6bba44bc-763b-4b0b-afd4-f0650a61b97d
  resourceVersion: "2445991"
  uid: ca7d7330-6100-4027-81fc-9a095330555b
type: Opaque
