apiVersion: v1
data:
  secret_key: ZEVGdk5rYmR4S1NIM1AxSUNhT2I5ZkNkOXEyaURCY2M=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Secret","metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/name":"ansible-awx","app.kubernetes.io/operator-version":"0.12.0","app.kubernetes.io/part-of":"ansible-awx"},"name":"ansible-awx-secret-key","namespace":"awx-namespace"},"stringData":{"secret_key":"dEFvNkbdxKSH3P1ICaOb9fCd9q2iDBcc"}}'
  creationTimestamp: "2021-10-25T23:21:23Z"
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: ansible-awx
    app.kubernetes.io/operator-version: 0.12.0
    app.kubernetes.io/part-of: ansible-awx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:secret_key: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/operator-version: {}
          f:app.kubernetes.io/part-of: {}
      f:type: {}
    manager: Swagger-Codegen
    operation: Update
    time: "2021-10-25T23:21:23Z"
  name: ansible-awx-secret-key
  namespace: awx-namespace
  resourceVersion: "2447786"
  uid: 11e12996-02e8-458c-ae4c-373dae98e802
type: Opaque
